# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(1158, 777)
		Form.setStyleSheet("background-color: rgb(214, 214, 214);")
		self.label = QtWidgets.QLabel(Form)
		self.label.setGeometry(QtCore.QRect(520, 100, 441, 61))
		self.label.setStyleSheet("color:rgb(84, 3, 135);\n"
"font: 16pt \"MS Shell Dlg 2\";")
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(Form)
		self.label_2.setGeometry(QtCore.QRect(210, 240, 201, 41))
		self.label_2.setStyleSheet("color:rgb(166, 4, 20);\n"
"font: 14pt \"MS Shell Dlg 2\";")
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(Form)
		self.label_3.setGeometry(QtCore.QRect(210, 300, 201, 41))
		self.label_3.setStyleSheet("color:rgb(166, 4, 20);\n"
"font: 14pt \"MS Shell Dlg 2\";")
		self.label_3.setObjectName("label_3")
		self.first_no = QtWidgets.QLineEdit(Form)
		self.first_no.setGeometry(QtCore.QRect(480, 240, 271, 41))
		self.first_no.setStyleSheet("color:rgb(0, 131, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
		self.first_no.setObjectName("first_no")
		self.second_no = QtWidgets.QLineEdit(Form)
		self.second_no.setGeometry(QtCore.QRect(480, 300, 271, 41))
		self.second_no.setStyleSheet("color:rgb(0, 131, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
		self.second_no.setObjectName("second_no")
		self.sum = QtWidgets.QPushButton(Form)
		self.sum.setGeometry(QtCore.QRect(210, 410, 91, 71))
		self.sum.setStyleSheet("color:rgb(166, 4, 20);\n"
"font: 14pt \"MS Shell Dlg 2\";")
		self.sum.setObjectName("sum")
		self.diff = QtWidgets.QPushButton(Form)
		self.diff.setGeometry(QtCore.QRect(210, 490, 91, 71))
		self.diff.setStyleSheet("color:rgb(166, 4, 20);\n"
"font: 14pt \"MS Shell Dlg 2\";")
		self.diff.setObjectName("diff")
		self.mul = QtWidgets.QPushButton(Form)
		self.mul.setGeometry(QtCore.QRect(210, 570, 91, 71))
		self.mul.setStyleSheet("color:rgb(166, 4, 20);\n"
"font: 14pt \"MS Shell Dlg 2\";")
		self.mul.setObjectName("mul")
		self.div = QtWidgets.QPushButton(Form)
		self.div.setGeometry(QtCore.QRect(210, 650, 91, 71))
		self.div.setStyleSheet("color:rgb(166, 4, 20);\n"
"font: 14pt \"MS Shell Dlg 2\";")
		self.div.setObjectName("div")
		self.res = QtWidgets.QLabel(Form)
		self.res.setGeometry(QtCore.QRect(470, 520, 281, 61))
		self.res.setStyleSheet("color:rgb(0, 131, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
		self.res.setObjectName("res")
		self.sum.clicked.connect(self.sumFun)
		self.diff.clicked.connect(self.diffFun)
		self.mul.clicked.connect(self.mulFun)
		self.div.clicked.connect(self.divFun)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def sumFun(self):
		print("Sum")
		a = self.first_no.text()
		b = self.second_no.text()
		if a.isnumeric() and b.isnumeric():
			self.res.setText(str(int(a)+int(b)))
		else:
			QMessageBox.information(None, "Error", "Enter only numbers")
	
	def diffFun(self):
		print("Diff")
		a = self.first_no.text()
		b = self.second_no.text()
		if a.isnumeric() and b.isnumeric():
			self.res.setText(str(int(a)-int(b)))
		else:
			QMessageBox.information(None, "Error", "Enter only numbers")

	def mulFun(self):
		print("Mul")
		a = self.first_no.text()
		b = self.second_no.text()
		if a.isnumeric() and b.isnumeric():
			self.res.setText(str(int(a)*int(b)))
		else:
			QMessageBox.information(None, "Error", "Enter only numbers")
	
	def divFun(self):
		print("Div")
		a = self.first_no.text()
		b = self.second_no.text()
		if a.isnumeric() and b.isnumeric():
			self.res.setText(str(int(a)/int(b)))
		else:
			QMessageBox.information(None, "Error", "Enter only numbers")

	def retranslateUi(self, Form):
		_translate = QtCore.QCoreApplication.translate
		Form.setWindowTitle(_translate("Form", "Form"))
		self.label.setText(_translate("Form", "Simple Calculator"))
		self.label_2.setText(_translate("Form", "First Number"))
		self.label_3.setText(_translate("Form", "Second Number"))
		self.sum.setText(_translate("Form", "+"))
		self.diff.setText(_translate("Form", "-"))
		self.mul.setText(_translate("Form", "*"))
		self.div.setText(_translate("Form", "/"))
		self.res.setText(_translate("Form", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
